<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Rep_return_detector_model extends CI_Model
{

	function getDetectorNational($data) {

        $inMonthArr = explode('-', $data['inmonth']);
        $lastMonthArr = explode('-', $data['lastmonth']);
        $threeMonthArr = explode('-', $data['threemonth']);

        $inMonthLastMonth = date('Y-m', strtotime('-1 month', strtotime($data['inmonth'])));
        $inMonthThreeMonth = date('Y-m', strtotime('-3 month', strtotime($data['inmonth'])));

        $lastMonthLastMonth = date('Y-m', strtotime('-1 month', strtotime($data['lastmonth'])));
        $lastMonthThreeMonth = date('Y-m', strtotime('-3 month', strtotime($data['lastmonth'])));

        $threeMonthLastMonth = date('Y-m', strtotime('-1 month', strtotime($data['threemonth'])));
        $threeMonthThreeMonth = date('Y-m', strtotime('-3 month', strtotime($data['threemonth'])));

        $inMonthLastMonthArr = explode('-', $inMonthLastMonth);
        $inMonthThreeMonthArr = explode('-', $inMonthThreeMonth);

        $lastMonthLastMonthArr = explode('-', $lastMonthLastMonth);
        $lastMonthThreeMonthArr = explode('-', $lastMonthThreeMonth);

        $threeMonthLastMonthArr = explode('-', $threeMonthLastMonth);
        $threeMonthThreeMonthArr = explode('-', $threeMonthThreeMonth);

        $where = "";

        if ($data['brandid'] != 'null') {
            $where = "d.brandid = '".$data['brandid']."' and";
            if ($data['productid'] != 'null') {
                $where = "d.productid = '".$data['productid']."' and";
            }
        }

        $sql = "select * from (
            select '".$data['inmonth']."' header, 'in_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and a.tahun between '".$inMonthArr[0]."' and '".$inMonthArr[0]."' and a.bulan between '".$inMonthArr[1]."' and '".$inMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and a.tahun between '".$inMonthArr[0]."' and '".$inMonthArr[0]."' and a.bulan between '".$inMonthArr[1]."' and '".$inMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and a.tahun between '".$inMonthArr[0]."' and '".$inMonthArr[0]."' and a.bulan between '".$inMonthArr[1]."' and '".$inMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and a.tahun between '".$inMonthArr[0]."' and '".$inMonthArr[0]."' and a.bulan between '".$inMonthArr[1]."' and '".$inMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and a.tahun between '".$inMonthArr[0]."' and '".$inMonthArr[0]."' and a.bulan between '".$inMonthArr[1]."' and '".$inMonthArr[1]."') sm 
            union all
            select '".$data['lastmonth']."' header, 'in_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and a.tahun between '".$lastMonthArr[0]."' and '".$lastMonthArr[0]."' and a.bulan between '".$lastMonthArr[1]."' and '".$lastMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and a.tahun between '".$lastMonthArr[0]."' and '".$lastMonthArr[0]."' and a.bulan between '".$lastMonthArr[1]."' and '".$lastMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and a.tahun between '".$lastMonthArr[0]."' and '".$lastMonthArr[0]."' and a.bulan between '".$lastMonthArr[1]."' and '".$lastMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and a.tahun between '".$lastMonthArr[0]."' and '".$lastMonthArr[0]."' and a.bulan between '".$lastMonthArr[1]."' and '".$lastMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and a.tahun between '".$lastMonthArr[0]."' and '".$lastMonthArr[0]."' and a.bulan between '".$lastMonthArr[1]."' and '".$lastMonthArr[1]."') sm
            union all
            select '".$data['threemonth']."' header, 'in_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and a.tahun between '".$threeMonthArr[0]."' and '".$threeMonthArr[0]."' and a.bulan between '".$threeMonthArr[1]."' and '".$threeMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and a.tahun between '".$threeMonthArr[0]."' and '".$threeMonthArr[0]."' and a.bulan between '".$threeMonthArr[1]."' and '".$threeMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and a.tahun between '".$threeMonthArr[0]."' and '".$threeMonthArr[0]."' and a.bulan between '".$threeMonthArr[1]."' and '".$threeMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and a.tahun between '".$threeMonthArr[0]."' and '".$threeMonthArr[0]."' and a.bulan between '".$threeMonthArr[1]."' and '".$threeMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and a.tahun between '".$threeMonthArr[0]."' and '".$threeMonthArr[0]."' and a.bulan between '".$threeMonthArr[1]."' and '".$threeMonthArr[1]."') sm
            union all
            select '".$data['inmonth']."' header, 'last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and a.tahun between '".$inMonthLastMonthArr[0]."' and '".$inMonthLastMonthArr[0]."' and a.bulan between '".$inMonthLastMonthArr[1]."' and '".$inMonthLastMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and a.tahun between '".$inMonthLastMonthArr[0]."' and '".$inMonthLastMonthArr[0]."' and a.bulan between '".$inMonthLastMonthArr[1]."' and '".$inMonthLastMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and a.tahun between '".$inMonthLastMonthArr[0]."' and '".$inMonthLastMonthArr[0]."' and a.bulan between '".$inMonthLastMonthArr[1]."' and '".$inMonthLastMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and a.tahun between '".$inMonthLastMonthArr[0]."' and '".$inMonthLastMonthArr[0]."' and a.bulan between '".$inMonthLastMonthArr[1]."' and '".$inMonthLastMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and a.tahun between '".$inMonthLastMonthArr[0]."' and '".$inMonthLastMonthArr[0]."' and a.bulan between '".$inMonthLastMonthArr[1]."' and '".$inMonthLastMonthArr[1]."') sm 
            union all
            select '".$data['lastmonth']."' header, 'last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and a.tahun between '".$lastMonthLastMonthArr[0]."' and '".$lastMonthLastMonthArr[0]."' and a.bulan between '".$lastMonthLastMonthArr[1]."' and '".$lastMonthLastMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and a.tahun between '".$lastMonthLastMonthArr[0]."' and '".$lastMonthLastMonthArr[0]."' and a.bulan between '".$lastMonthLastMonthArr[1]."' and '".$lastMonthLastMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and a.tahun between '".$lastMonthLastMonthArr[0]."' and '".$lastMonthLastMonthArr[0]."' and a.bulan between '".$lastMonthLastMonthArr[1]."' and '".$lastMonthLastMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and a.tahun between '".$lastMonthLastMonthArr[0]."' and '".$lastMonthLastMonthArr[0]."' and a.bulan between '".$lastMonthLastMonthArr[1]."' and '".$lastMonthLastMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and a.tahun between '".$lastMonthLastMonthArr[0]."' and '".$lastMonthLastMonthArr[0]."' and a.bulan between '".$lastMonthLastMonthArr[1]."' and '".$lastMonthLastMonthArr[1]."') sm
            union all
            select '".$data['threemonth']."' header, 'last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and a.tahun between '".$threeMonthLastMonthArr[0]."' and '".$threeMonthLastMonthArr[0]."' and a.bulan between '".$threeMonthLastMonthArr[1]."' and '".$threeMonthLastMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and a.tahun between '".$threeMonthLastMonthArr[0]."' and '".$threeMonthLastMonthArr[0]."' and a.bulan between '".$threeMonthLastMonthArr[1]."' and '".$threeMonthLastMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and a.tahun between '".$threeMonthLastMonthArr[0]."' and '".$threeMonthLastMonthArr[0]."' and a.bulan between '".$threeMonthLastMonthArr[1]."' and '".$threeMonthLastMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and a.tahun between '".$threeMonthLastMonthArr[0]."' and '".$threeMonthLastMonthArr[0]."' and a.bulan between '".$threeMonthLastMonthArr[1]."' and '".$threeMonthLastMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and a.tahun between '".$threeMonthLastMonthArr[0]."' and '".$threeMonthLastMonthArr[0]."' and a.bulan between '".$threeMonthLastMonthArr[1]."' and '".$threeMonthLastMonthArr[1]."') sm
            union all
            select '".$data['inmonth']."' header, 'three_last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and a.tahun between '".$inMonthThreeMonthArr[0]."' and '".$inMonthThreeMonthArr[0]."' and a.bulan between '".$inMonthThreeMonthArr[1]."' and '".$inMonthThreeMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and a.tahun between '".$inMonthThreeMonthArr[0]."' and '".$inMonthThreeMonthArr[0]."' and a.bulan between '".$inMonthThreeMonthArr[1]."' and '".$inMonthThreeMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and a.tahun between '".$inMonthThreeMonthArr[0]."' and '".$inMonthThreeMonthArr[0]."' and a.bulan between '".$inMonthThreeMonthArr[1]."' and '".$inMonthThreeMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and a.tahun between '".$inMonthThreeMonthArr[0]."' and '".$inMonthThreeMonthArr[0]."' and a.bulan between '".$inMonthThreeMonthArr[1]."' and '".$inMonthThreeMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and a.tahun between '".$inMonthThreeMonthArr[0]."' and '".$inMonthThreeMonthArr[0]."' and a.bulan between '".$inMonthThreeMonthArr[1]."' and '".$inMonthThreeMonthArr[1]."') sm 
            union all
            select '".$data['lastmonth']."' header, 'three_last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and a.tahun between '".$lastMonthThreeMonthArr[0]."' and '".$lastMonthThreeMonthArr[0]."' and a.bulan between '".$lastMonthThreeMonthArr[1]."' and '".$lastMonthThreeMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and a.tahun between '".$lastMonthThreeMonthArr[0]."' and '".$lastMonthThreeMonthArr[0]."' and a.bulan between '".$lastMonthThreeMonthArr[1]."' and '".$lastMonthThreeMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and a.tahun between '".$lastMonthThreeMonthArr[0]."' and '".$lastMonthThreeMonthArr[0]."' and a.bulan between '".$lastMonthThreeMonthArr[1]."' and '".$lastMonthThreeMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and a.tahun between '".$lastMonthThreeMonthArr[0]."' and '".$lastMonthThreeMonthArr[0]."' and a.bulan between '".$lastMonthThreeMonthArr[1]."' and '".$lastMonthThreeMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and a.tahun between '".$lastMonthThreeMonthArr[0]."' and '".$lastMonthThreeMonthArr[0]."' and a.bulan between '".$lastMonthThreeMonthArr[1]."' and '".$lastMonthThreeMonthArr[1]."') sm
            union all
            select '".$data['threemonth']."' header, 'three_last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and a.tahun between '".$threeMonthThreeMonthArr[0]."' and '".$threeMonthThreeMonthArr[0]."' and a.bulan between '".$threeMonthThreeMonthArr[1]."' and '".$threeMonthThreeMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and a.tahun between '".$threeMonthThreeMonthArr[0]."' and '".$threeMonthThreeMonthArr[0]."' and a.bulan between '".$threeMonthThreeMonthArr[1]."' and '".$threeMonthThreeMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and a.tahun between '".$threeMonthThreeMonthArr[0]."' and '".$threeMonthThreeMonthArr[0]."' and a.bulan between '".$threeMonthThreeMonthArr[1]."' and '".$threeMonthThreeMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and a.tahun between '".$threeMonthThreeMonthArr[0]."' and '".$threeMonthThreeMonthArr[0]."' and a.bulan between '".$threeMonthThreeMonthArr[1]."' and '".$threeMonthThreeMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and a.tahun between '".$threeMonthThreeMonthArr[0]."' and '".$threeMonthThreeMonthArr[0]."' and a.bulan between '".$threeMonthThreeMonthArr[1]."' and '".$threeMonthThreeMonthArr[1]."') sm
            ) x order by x.header_left asc";

        $query = $this->db->query($sql);

        return $query->result_array();
    }

    function getDetectorRegional($data) {

    	$inMonthArr = explode('-', $data['inmonth']);
    	$lastMonthArr = explode('-', $data['lastmonth']);
    	$threeMonthArr = explode('-', $data['threemonth']);

    	$inMonthLastMonth = date('Y-m', strtotime('-1 month', strtotime($data['inmonth'])));
    	$inMonthThreeMonth = date('Y-m', strtotime('-3 month', strtotime($data['inmonth'])));

    	$lastMonthLastMonth = date('Y-m', strtotime('-1 month', strtotime($data['lastmonth'])));
    	$lastMonthThreeMonth = date('Y-m', strtotime('-3 month', strtotime($data['lastmonth'])));

    	$threeMonthLastMonth = date('Y-m', strtotime('-1 month', strtotime($data['threemonth'])));
    	$threeMonthThreeMonth = date('Y-m', strtotime('-3 month', strtotime($data['threemonth'])));

    	$inMonthLastMonthArr = explode('-', $inMonthLastMonth);
    	$inMonthThreeMonthArr = explode('-', $inMonthThreeMonth);

    	$lastMonthLastMonthArr = explode('-', $lastMonthLastMonth);
    	$lastMonthThreeMonthArr = explode('-', $lastMonthThreeMonth);

    	$threeMonthLastMonthArr = explode('-', $threeMonthLastMonth);
    	$threeMonthThreeMonthArr = explode('-', $threeMonthThreeMonth);

        $where = "";

        if ($data['brandid'] != 'null') {
            $where = "d.brandid = '".$data['brandid']."' and";
            if ($data['productid'] != 'null') {
                $where = "a.productid = '".$data['productid']."' and";
            }
        }

    	$sql = "select * from (
			select r.regionalid,r.nama_regional, '".$data['inmonth']."' header, 'in_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.regionalid = r.regionalid and a.tahun between '".$inMonthArr[0]."' and '".$inMonthArr[0]."' and a.bulan between '".$inMonthArr[1]."' and '".$inMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.regionalid = r.regionalid and a.tahun between '".$inMonthArr[0]."' and '".$inMonthArr[0]."' and a.bulan between '".$inMonthArr[1]."' and '".$inMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.regionalid = r.regionalid and a.tahun between '".$inMonthArr[0]."' and '".$inMonthArr[0]."' and a.bulan between '".$inMonthArr[1]."' and '".$inMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.regionalid = r.regionalid and a.tahun between '".$inMonthArr[0]."' and '".$inMonthArr[0]."' and a.bulan between '".$inMonthArr[1]."' and '".$inMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.regionalid = r.regionalid and a.tahun between '".$inMonthArr[0]."' and '".$inMonthArr[0]."' and a.bulan between '".$inMonthArr[1]."' and '".$inMonthArr[1]."') sm from m_area_regional r 
			union all
			select r.regionalid,r.nama_regional, '".$data['lastmonth']."' header, 'in_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.regionalid = r.regionalid and a.tahun between '".$lastMonthArr[0]."' and '".$lastMonthArr[0]."' and a.bulan between '".$lastMonthArr[1]."' and '".$lastMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.regionalid = r.regionalid and a.tahun between '".$lastMonthArr[0]."' and '".$lastMonthArr[0]."' and a.bulan between '".$lastMonthArr[1]."' and '".$lastMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.regionalid = r.regionalid and a.tahun between '".$lastMonthArr[0]."' and '".$lastMonthArr[0]."' and a.bulan between '".$lastMonthArr[1]."' and '".$lastMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.regionalid = r.regionalid and a.tahun between '".$lastMonthArr[0]."' and '".$lastMonthArr[0]."' and a.bulan between '".$lastMonthArr[1]."' and '".$lastMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.regionalid = r.regionalid and a.tahun between '".$lastMonthArr[0]."' and '".$lastMonthArr[0]."' and a.bulan between '".$lastMonthArr[1]."' and '".$lastMonthArr[1]."') sm from m_area_regional r
			union all
			select r.regionalid,r.nama_regional, '".$data['threemonth']."' header, 'in_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.regionalid = r.regionalid and a.tahun between '".$threeMonthArr[0]."' and '".$threeMonthArr[0]."' and a.bulan between '".$threeMonthArr[1]."' and '".$threeMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.regionalid = r.regionalid and a.tahun between '".$threeMonthArr[0]."' and '".$threeMonthArr[0]."' and a.bulan between '".$threeMonthArr[1]."' and '".$threeMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.regionalid = r.regionalid and a.tahun between '".$threeMonthArr[0]."' and '".$threeMonthArr[0]."' and a.bulan between '".$threeMonthArr[1]."' and '".$threeMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.regionalid = r.regionalid and a.tahun between '".$threeMonthArr[0]."' and '".$threeMonthArr[0]."' and a.bulan between '".$threeMonthArr[1]."' and '".$threeMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.regionalid = r.regionalid and a.tahun between '".$threeMonthArr[0]."' and '".$threeMonthArr[0]."' and a.bulan between '".$threeMonthArr[1]."' and '".$threeMonthArr[1]."') sm from m_area_regional r
			union all
			select r.regionalid,r.nama_regional, '".$data['inmonth']."' header, 'last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.regionalid = r.regionalid and a.tahun between '".$inMonthLastMonthArr[0]."' and '".$inMonthLastMonthArr[0]."' and a.bulan between '".$inMonthLastMonthArr[1]."' and '".$inMonthLastMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.regionalid = r.regionalid and a.tahun between '".$inMonthLastMonthArr[0]."' and '".$inMonthLastMonthArr[0]."' and a.bulan between '".$inMonthLastMonthArr[1]."' and '".$inMonthLastMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.regionalid = r.regionalid and a.tahun between '".$inMonthLastMonthArr[0]."' and '".$inMonthLastMonthArr[0]."' and a.bulan between '".$inMonthLastMonthArr[1]."' and '".$inMonthLastMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.regionalid = r.regionalid and a.tahun between '".$inMonthLastMonthArr[0]."' and '".$inMonthLastMonthArr[0]."' and a.bulan between '".$inMonthLastMonthArr[1]."' and '".$inMonthLastMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.regionalid = r.regionalid and a.tahun between '".$inMonthLastMonthArr[0]."' and '".$inMonthLastMonthArr[0]."' and a.bulan between '".$inMonthLastMonthArr[1]."' and '".$inMonthLastMonthArr[1]."') sm from m_area_regional r 
			union all
			select r.regionalid,r.nama_regional, '".$data['lastmonth']."' header, 'last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.regionalid = r.regionalid and a.tahun between '".$lastMonthLastMonthArr[0]."' and '".$lastMonthLastMonthArr[0]."' and a.bulan between '".$lastMonthLastMonthArr[1]."' and '".$lastMonthLastMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.regionalid = r.regionalid and a.tahun between '".$lastMonthLastMonthArr[0]."' and '".$lastMonthLastMonthArr[0]."' and a.bulan between '".$lastMonthLastMonthArr[1]."' and '".$lastMonthLastMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.regionalid = r.regionalid and a.tahun between '".$lastMonthLastMonthArr[0]."' and '".$lastMonthLastMonthArr[0]."' and a.bulan between '".$lastMonthLastMonthArr[1]."' and '".$lastMonthLastMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.regionalid = r.regionalid and a.tahun between '".$lastMonthLastMonthArr[0]."' and '".$lastMonthLastMonthArr[0]."' and a.bulan between '".$lastMonthLastMonthArr[1]."' and '".$lastMonthLastMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.regionalid = r.regionalid and a.tahun between '".$lastMonthLastMonthArr[0]."' and '".$lastMonthLastMonthArr[0]."' and a.bulan between '".$lastMonthLastMonthArr[1]."' and '".$lastMonthLastMonthArr[1]."') sm from m_area_regional r
			union all
			select r.regionalid,r.nama_regional, '".$data['threemonth']."' header, 'last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.regionalid = r.regionalid and a.tahun between '".$threeMonthLastMonthArr[0]."' and '".$threeMonthLastMonthArr[0]."' and a.bulan between '".$threeMonthLastMonthArr[1]."' and '".$threeMonthLastMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.regionalid = r.regionalid and a.tahun between '".$threeMonthLastMonthArr[0]."' and '".$threeMonthLastMonthArr[0]."' and a.bulan between '".$threeMonthLastMonthArr[1]."' and '".$threeMonthLastMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.regionalid = r.regionalid and a.tahun between '".$threeMonthLastMonthArr[0]."' and '".$threeMonthLastMonthArr[0]."' and a.bulan between '".$threeMonthLastMonthArr[1]."' and '".$threeMonthLastMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.regionalid = r.regionalid and a.tahun between '".$threeMonthLastMonthArr[0]."' and '".$threeMonthLastMonthArr[0]."' and a.bulan between '".$threeMonthLastMonthArr[1]."' and '".$threeMonthLastMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.regionalid = r.regionalid and a.tahun between '".$threeMonthLastMonthArr[0]."' and '".$threeMonthLastMonthArr[0]."' and a.bulan between '".$threeMonthLastMonthArr[1]."' and '".$threeMonthLastMonthArr[1]."') sm from m_area_regional r
			union all
			select r.regionalid,r.nama_regional, '".$data['inmonth']."' header, 'three_last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.regionalid = r.regionalid and a.tahun between '".$inMonthThreeMonthArr[0]."' and '".$inMonthThreeMonthArr[0]."' and a.bulan between '".$inMonthThreeMonthArr[1]."' and '".$inMonthThreeMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.regionalid = r.regionalid and a.tahun between '".$inMonthThreeMonthArr[0]."' and '".$inMonthThreeMonthArr[0]."' and a.bulan between '".$inMonthThreeMonthArr[1]."' and '".$inMonthThreeMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.regionalid = r.regionalid and a.tahun between '".$inMonthThreeMonthArr[0]."' and '".$inMonthThreeMonthArr[0]."' and a.bulan between '".$inMonthThreeMonthArr[1]."' and '".$inMonthThreeMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.regionalid = r.regionalid and a.tahun between '".$inMonthThreeMonthArr[0]."' and '".$inMonthThreeMonthArr[0]."' and a.bulan between '".$inMonthThreeMonthArr[1]."' and '".$inMonthThreeMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.regionalid = r.regionalid and a.tahun between '".$inMonthThreeMonthArr[0]."' and '".$inMonthThreeMonthArr[0]."' and a.bulan between '".$inMonthThreeMonthArr[1]."' and '".$inMonthThreeMonthArr[1]."') sm from m_area_regional r 
			union all
			select r.regionalid,r.nama_regional, '".$data['lastmonth']."' header, 'three_last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.regionalid = r.regionalid and a.tahun between '".$lastMonthThreeMonthArr[0]."' and '".$lastMonthThreeMonthArr[0]."' and a.bulan between '".$lastMonthThreeMonthArr[1]."' and '".$lastMonthThreeMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.regionalid = r.regionalid and a.tahun between '".$lastMonthThreeMonthArr[0]."' and '".$lastMonthThreeMonthArr[0]."' and a.bulan between '".$lastMonthThreeMonthArr[1]."' and '".$lastMonthThreeMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.regionalid = r.regionalid and a.tahun between '".$lastMonthThreeMonthArr[0]."' and '".$lastMonthThreeMonthArr[0]."' and a.bulan between '".$lastMonthThreeMonthArr[1]."' and '".$lastMonthThreeMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.regionalid = r.regionalid and a.tahun between '".$lastMonthThreeMonthArr[0]."' and '".$lastMonthThreeMonthArr[0]."' and a.bulan between '".$lastMonthThreeMonthArr[1]."' and '".$lastMonthThreeMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.regionalid = r.regionalid and a.tahun between '".$lastMonthThreeMonthArr[0]."' and '".$lastMonthThreeMonthArr[0]."' and a.bulan between '".$lastMonthThreeMonthArr[1]."' and '".$lastMonthThreeMonthArr[1]."') sm from m_area_regional r
			union all
			select r.regionalid,r.nama_regional, '".$data['threemonth']."' header, 'three_last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.regionalid = r.regionalid and a.tahun between '".$threeMonthThreeMonthArr[0]."' and '".$threeMonthThreeMonthArr[0]."' and a.bulan between '".$threeMonthThreeMonthArr[1]."' and '".$threeMonthThreeMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.regionalid = r.regionalid and a.tahun between '".$threeMonthThreeMonthArr[0]."' and '".$threeMonthThreeMonthArr[0]."' and a.bulan between '".$threeMonthThreeMonthArr[1]."' and '".$threeMonthThreeMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.regionalid = r.regionalid and a.tahun between '".$threeMonthThreeMonthArr[0]."' and '".$threeMonthThreeMonthArr[0]."' and a.bulan between '".$threeMonthThreeMonthArr[1]."' and '".$threeMonthThreeMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.regionalid = r.regionalid and a.tahun between '".$threeMonthThreeMonthArr[0]."' and '".$threeMonthThreeMonthArr[0]."' and a.bulan between '".$threeMonthThreeMonthArr[1]."' and '".$threeMonthThreeMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_regional c on b.regionalid = c.regionalid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.regionalid = r.regionalid and a.tahun between '".$threeMonthThreeMonthArr[0]."' and '".$threeMonthThreeMonthArr[0]."' and a.bulan between '".$threeMonthThreeMonthArr[1]."' and '".$threeMonthThreeMonthArr[1]."') sm from m_area_regional r
			) x order by x.regionalid, x.header_left asc";

		$query = $this->db->query($sql);

		return $query->result_array();
	}

    function getDetectorArea($data) {
        $inMonthArr = explode('-', $data['inmonth']);
        $lastMonthArr = explode('-', $data['lastmonth']);
        $threeMonthArr = explode('-', $data['threemonth']);

        $inMonthLastMonth = date('Y-m', strtotime('-1 month', strtotime($data['inmonth'])));
        $inMonthThreeMonth = date('Y-m', strtotime('-3 month', strtotime($data['inmonth'])));

        $lastMonthLastMonth = date('Y-m', strtotime('-1 month', strtotime($data['lastmonth'])));
        $lastMonthThreeMonth = date('Y-m', strtotime('-3 month', strtotime($data['lastmonth'])));

        $threeMonthLastMonth = date('Y-m', strtotime('-1 month', strtotime($data['threemonth'])));
        $threeMonthThreeMonth = date('Y-m', strtotime('-3 month', strtotime($data['threemonth'])));

        $inMonthLastMonthArr = explode('-', $inMonthLastMonth);
        $inMonthThreeMonthArr = explode('-', $inMonthThreeMonth);

        $lastMonthLastMonthArr = explode('-', $lastMonthLastMonth);
        $lastMonthThreeMonthArr = explode('-', $lastMonthThreeMonth);

        $threeMonthLastMonthArr = explode('-', $threeMonthLastMonth);
        $threeMonthThreeMonthArr = explode('-', $threeMonthThreeMonth);

        $where = "";

        if ($data['brandid'] != 'null') {
            $where = "d.brandid = '".$data['brandid']."' and";
            if ($data['productid'] != 'null') {
                $where = "d.productid = '".$data['productid']."' and";
            }
        }

        $sql = "select * from (
            select r.areaid,r.nama_area, '".$data['inmonth']."' header, 'in_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.areaid = r.areaid and a.tahun between '".$inMonthArr[0]."' and '".$inMonthArr[0]."' and a.bulan between '".$inMonthArr[1]."' and '".$inMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.areaid = r.areaid and a.tahun between '".$inMonthArr[0]."' and '".$inMonthArr[0]."' and a.bulan between '".$inMonthArr[1]."' and '".$inMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.areaid = r.areaid and a.tahun between '".$inMonthArr[0]."' and '".$inMonthArr[0]."' and a.bulan between '".$inMonthArr[1]."' and '".$inMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.areaid = r.areaid and a.tahun between '".$inMonthArr[0]."' and '".$inMonthArr[0]."' and a.bulan between '".$inMonthArr[1]."' and '".$inMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.areaid = r.areaid and a.tahun between '".$inMonthArr[0]."' and '".$inMonthArr[0]."' and a.bulan between '".$inMonthArr[1]."' and '".$inMonthArr[1]."') sm from m_area_areasite r where r.regionalid = '".$data['regionalid']."' 
            union all
            select r.areaid,r.nama_area, '".$data['lastmonth']."' header, 'in_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.areaid = r.areaid and a.tahun between '".$lastMonthArr[0]."' and '".$lastMonthArr[0]."' and a.bulan between '".$lastMonthArr[1]."' and '".$lastMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.areaid = r.areaid and a.tahun between '".$lastMonthArr[0]."' and '".$lastMonthArr[0]."' and a.bulan between '".$lastMonthArr[1]."' and '".$lastMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.areaid = r.areaid and a.tahun between '".$lastMonthArr[0]."' and '".$lastMonthArr[0]."' and a.bulan between '".$lastMonthArr[1]."' and '".$lastMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.areaid = r.areaid and a.tahun between '".$lastMonthArr[0]."' and '".$lastMonthArr[0]."' and a.bulan between '".$lastMonthArr[1]."' and '".$lastMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.areaid = r.areaid and a.tahun between '".$lastMonthArr[0]."' and '".$lastMonthArr[0]."' and a.bulan between '".$lastMonthArr[1]."' and '".$lastMonthArr[1]."') sm from m_area_areasite r where r.regionalid = '".$data['regionalid']."'
            union all
            select r.areaid,r.nama_area, '".$data['threemonth']."' header, 'in_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.areaid = r.areaid and a.tahun between '".$threeMonthArr[0]."' and '".$threeMonthArr[0]."' and a.bulan between '".$threeMonthArr[1]."' and '".$threeMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.areaid = r.areaid and a.tahun between '".$threeMonthArr[0]."' and '".$threeMonthArr[0]."' and a.bulan between '".$threeMonthArr[1]."' and '".$threeMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.areaid = r.areaid and a.tahun between '".$threeMonthArr[0]."' and '".$threeMonthArr[0]."' and a.bulan between '".$threeMonthArr[1]."' and '".$threeMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.areaid = r.areaid and a.tahun between '".$threeMonthArr[0]."' and '".$threeMonthArr[0]."' and a.bulan between '".$threeMonthArr[1]."' and '".$threeMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.areaid = r.areaid and a.tahun between '".$threeMonthArr[0]."' and '".$threeMonthArr[0]."' and a.bulan between '".$threeMonthArr[1]."' and '".$threeMonthArr[1]."') sm from m_area_areasite r where r.regionalid = '".$data['regionalid']."'
            union all
            select r.areaid,r.nama_area, '".$data['inmonth']."' header, 'last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.areaid = r.areaid and a.tahun between '".$inMonthLastMonthArr[0]."' and '".$inMonthLastMonthArr[0]."' and a.bulan between '".$inMonthLastMonthArr[1]."' and '".$inMonthLastMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.areaid = r.areaid and a.tahun between '".$inMonthLastMonthArr[0]."' and '".$inMonthLastMonthArr[0]."' and a.bulan between '".$inMonthLastMonthArr[1]."' and '".$inMonthLastMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.areaid = r.areaid and a.tahun between '".$inMonthLastMonthArr[0]."' and '".$inMonthLastMonthArr[0]."' and a.bulan between '".$inMonthLastMonthArr[1]."' and '".$inMonthLastMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.areaid = r.areaid and a.tahun between '".$inMonthLastMonthArr[0]."' and '".$inMonthLastMonthArr[0]."' and a.bulan between '".$inMonthLastMonthArr[1]."' and '".$inMonthLastMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.areaid = r.areaid and a.tahun between '".$inMonthLastMonthArr[0]."' and '".$inMonthLastMonthArr[0]."' and a.bulan between '".$inMonthLastMonthArr[1]."' and '".$inMonthLastMonthArr[1]."') sm from m_area_areasite r where r.regionalid = '".$data['regionalid']."' 
            union all
            select r.areaid,r.nama_area, '".$data['lastmonth']."' header, 'last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.areaid = r.areaid and a.tahun between '".$lastMonthLastMonthArr[0]."' and '".$lastMonthLastMonthArr[0]."' and a.bulan between '".$lastMonthLastMonthArr[1]."' and '".$lastMonthLastMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.areaid = r.areaid and a.tahun between '".$lastMonthLastMonthArr[0]."' and '".$lastMonthLastMonthArr[0]."' and a.bulan between '".$lastMonthLastMonthArr[1]."' and '".$lastMonthLastMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.areaid = r.areaid and a.tahun between '".$lastMonthLastMonthArr[0]."' and '".$lastMonthLastMonthArr[0]."' and a.bulan between '".$lastMonthLastMonthArr[1]."' and '".$lastMonthLastMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.areaid = r.areaid and a.tahun between '".$lastMonthLastMonthArr[0]."' and '".$lastMonthLastMonthArr[0]."' and a.bulan between '".$lastMonthLastMonthArr[1]."' and '".$lastMonthLastMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.areaid = r.areaid and a.tahun between '".$lastMonthLastMonthArr[0]."' and '".$lastMonthLastMonthArr[0]."' and a.bulan between '".$lastMonthLastMonthArr[1]."' and '".$lastMonthLastMonthArr[1]."') sm from m_area_areasite r where r.regionalid = '".$data['regionalid']."'
            union all
            select r.areaid,r.nama_area, '".$data['threemonth']."' header, 'last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.areaid = r.areaid and a.tahun between '".$threeMonthLastMonthArr[0]."' and '".$threeMonthLastMonthArr[0]."' and a.bulan between '".$threeMonthLastMonthArr[1]."' and '".$threeMonthLastMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.areaid = r.areaid and a.tahun between '".$threeMonthLastMonthArr[0]."' and '".$threeMonthLastMonthArr[0]."' and a.bulan between '".$threeMonthLastMonthArr[1]."' and '".$threeMonthLastMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.areaid = r.areaid and a.tahun between '".$threeMonthLastMonthArr[0]."' and '".$threeMonthLastMonthArr[0]."' and a.bulan between '".$threeMonthLastMonthArr[1]."' and '".$threeMonthLastMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.areaid = r.areaid and a.tahun between '".$threeMonthLastMonthArr[0]."' and '".$threeMonthLastMonthArr[0]."' and a.bulan between '".$threeMonthLastMonthArr[1]."' and '".$threeMonthLastMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.areaid = r.areaid and a.tahun between '".$threeMonthLastMonthArr[0]."' and '".$threeMonthLastMonthArr[0]."' and a.bulan between '".$threeMonthLastMonthArr[1]."' and '".$threeMonthLastMonthArr[1]."') sm from m_area_areasite r where r.regionalid = '".$data['regionalid']."'
            union all
            select r.areaid,r.nama_area, '".$data['inmonth']."' header, 'three_last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.areaid = r.areaid and a.tahun between '".$inMonthThreeMonthArr[0]."' and '".$inMonthThreeMonthArr[0]."' and a.bulan between '".$inMonthThreeMonthArr[1]."' and '".$inMonthThreeMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.areaid = r.areaid and a.tahun between '".$inMonthThreeMonthArr[0]."' and '".$inMonthThreeMonthArr[0]."' and a.bulan between '".$inMonthThreeMonthArr[1]."' and '".$inMonthThreeMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.areaid = r.areaid and a.tahun between '".$inMonthThreeMonthArr[0]."' and '".$inMonthThreeMonthArr[0]."' and a.bulan between '".$inMonthThreeMonthArr[1]."' and '".$inMonthThreeMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.areaid = r.areaid and a.tahun between '".$inMonthThreeMonthArr[0]."' and '".$inMonthThreeMonthArr[0]."' and a.bulan between '".$inMonthThreeMonthArr[1]."' and '".$inMonthThreeMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.areaid = r.areaid and a.tahun between '".$inMonthThreeMonthArr[0]."' and '".$inMonthThreeMonthArr[0]."' and a.bulan between '".$inMonthThreeMonthArr[1]."' and '".$inMonthThreeMonthArr[1]."') sm from m_area_areasite r where r.regionalid = '".$data['regionalid']."' 
            union all
            select r.areaid,r.nama_area, '".$data['lastmonth']."' header, 'three_last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.areaid = r.areaid and a.tahun between '".$lastMonthThreeMonthArr[0]."' and '".$lastMonthThreeMonthArr[0]."' and a.bulan between '".$lastMonthThreeMonthArr[1]."' and '".$lastMonthThreeMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.areaid = r.areaid and a.tahun between '".$lastMonthThreeMonthArr[0]."' and '".$lastMonthThreeMonthArr[0]."' and a.bulan between '".$lastMonthThreeMonthArr[1]."' and '".$lastMonthThreeMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.areaid = r.areaid and a.tahun between '".$lastMonthThreeMonthArr[0]."' and '".$lastMonthThreeMonthArr[0]."' and a.bulan between '".$lastMonthThreeMonthArr[1]."' and '".$lastMonthThreeMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.areaid = r.areaid and a.tahun between '".$lastMonthThreeMonthArr[0]."' and '".$lastMonthThreeMonthArr[0]."' and a.bulan between '".$lastMonthThreeMonthArr[1]."' and '".$lastMonthThreeMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.areaid = r.areaid and a.tahun between '".$lastMonthThreeMonthArr[0]."' and '".$lastMonthThreeMonthArr[0]."' and a.bulan between '".$lastMonthThreeMonthArr[1]."' and '".$lastMonthThreeMonthArr[1]."') sm from m_area_areasite r where r.regionalid = '".$data['regionalid']."'
            union all
            select r.areaid,r.nama_area, '".$data['threemonth']."' header, 'three_last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.areaid = r.areaid and a.tahun between '".$threeMonthThreeMonthArr[0]."' and '".$threeMonthThreeMonthArr[0]."' and a.bulan between '".$threeMonthThreeMonthArr[1]."' and '".$threeMonthThreeMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.areaid = r.areaid and a.tahun between '".$threeMonthThreeMonthArr[0]."' and '".$threeMonthThreeMonthArr[0]."' and a.bulan between '".$threeMonthThreeMonthArr[1]."' and '".$threeMonthThreeMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.areaid = r.areaid and a.tahun between '".$threeMonthThreeMonthArr[0]."' and '".$threeMonthThreeMonthArr[0]."' and a.bulan between '".$threeMonthThreeMonthArr[1]."' and '".$threeMonthThreeMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.areaid = r.areaid and a.tahun between '".$threeMonthThreeMonthArr[0]."' and '".$threeMonthThreeMonthArr[0]."' and a.bulan between '".$threeMonthThreeMonthArr[1]."' and '".$threeMonthThreeMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_areasite c on b.areaid = c.areaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.areaid = r.areaid and a.tahun between '".$threeMonthThreeMonthArr[0]."' and '".$threeMonthThreeMonthArr[0]."' and a.bulan between '".$threeMonthThreeMonthArr[1]."' and '".$threeMonthThreeMonthArr[1]."') sm from m_area_areasite r where r.regionalid = '".$data['regionalid']."'
            ) x order by x.areaid, x.header_left asc";

        $query = $this->db->query($sql);

        return $query->result_array();
    }

    function getDetectorSubArea($data) {
        $inMonthArr = explode('-', $data['inmonth']);
        $lastMonthArr = explode('-', $data['lastmonth']);
        $threeMonthArr = explode('-', $data['threemonth']);

        $inMonthLastMonth = date('Y-m', strtotime('-1 month', strtotime($data['inmonth'])));
        $inMonthThreeMonth = date('Y-m', strtotime('-3 month', strtotime($data['inmonth'])));

        $lastMonthLastMonth = date('Y-m', strtotime('-1 month', strtotime($data['lastmonth'])));
        $lastMonthThreeMonth = date('Y-m', strtotime('-3 month', strtotime($data['lastmonth'])));

        $threeMonthLastMonth = date('Y-m', strtotime('-1 month', strtotime($data['threemonth'])));
        $threeMonthThreeMonth = date('Y-m', strtotime('-3 month', strtotime($data['threemonth'])));

        $inMonthLastMonthArr = explode('-', $inMonthLastMonth);
        $inMonthThreeMonthArr = explode('-', $inMonthThreeMonth);

        $lastMonthLastMonthArr = explode('-', $lastMonthLastMonth);
        $lastMonthThreeMonthArr = explode('-', $lastMonthThreeMonth);

        $threeMonthLastMonthArr = explode('-', $threeMonthLastMonth);
        $threeMonthThreeMonthArr = explode('-', $threeMonthThreeMonth);

        $where = "";

        if ($data['brandid'] != 'null') {
            $where = "d.brandid = '".$data['brandid']."' and";
            if ($data['productid'] != 'null') {
                $where = "a.productid = '".$data['productid']."' and";
            }
        }

        $sql = "select * from (
            select r.subareaid,r.nama_area, '".$data['inmonth']."' header, 'in_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.subareaid = r.subareaid and a.tahun between '".$inMonthArr[0]."' and '".$inMonthArr[0]."' and a.bulan between '".$inMonthArr[1]."' and '".$inMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.subareaid = r.subareaid and a.tahun between '".$inMonthArr[0]."' and '".$inMonthArr[0]."' and a.bulan between '".$inMonthArr[1]."' and '".$inMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.subareaid = r.subareaid and a.tahun between '".$inMonthArr[0]."' and '".$inMonthArr[0]."' and a.bulan between '".$inMonthArr[1]."' and '".$inMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.subareaid = r.subareaid and a.tahun between '".$inMonthArr[0]."' and '".$inMonthArr[0]."' and a.bulan between '".$inMonthArr[1]."' and '".$inMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.subareaid = r.subareaid and a.tahun between '".$inMonthArr[0]."' and '".$inMonthArr[0]."' and a.bulan between '".$inMonthArr[1]."' and '".$inMonthArr[1]."') sm from m_area_subarea r where r.regionalid = '".$data['regionalid']."' and r.areaid = '".$data['areaid']."'
            union all
            select r.subareaid,r.nama_area, '".$data['lastmonth']."' header, 'in_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.subareaid = r.subareaid and a.tahun between '".$lastMonthArr[0]."' and '".$lastMonthArr[0]."' and a.bulan between '".$lastMonthArr[1]."' and '".$lastMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.subareaid = r.subareaid and a.tahun between '".$lastMonthArr[0]."' and '".$lastMonthArr[0]."' and a.bulan between '".$lastMonthArr[1]."' and '".$lastMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.subareaid = r.subareaid and a.tahun between '".$lastMonthArr[0]."' and '".$lastMonthArr[0]."' and a.bulan between '".$lastMonthArr[1]."' and '".$lastMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.subareaid = r.subareaid and a.tahun between '".$lastMonthArr[0]."' and '".$lastMonthArr[0]."' and a.bulan between '".$lastMonthArr[1]."' and '".$lastMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.subareaid = r.subareaid and a.tahun between '".$lastMonthArr[0]."' and '".$lastMonthArr[0]."' and a.bulan between '".$lastMonthArr[1]."' and '".$lastMonthArr[1]."') sm from m_area_subarea r where r.regionalid = '".$data['regionalid']."' and r.areaid = '".$data['areaid']."'
            union all
            select r.subareaid,r.nama_area, '".$data['threemonth']."' header, 'in_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.subareaid = r.subareaid and a.tahun between '".$threeMonthArr[0]."' and '".$threeMonthArr[0]."' and a.bulan between '".$threeMonthArr[1]."' and '".$threeMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.subareaid = r.subareaid and a.tahun between '".$threeMonthArr[0]."' and '".$threeMonthArr[0]."' and a.bulan between '".$threeMonthArr[1]."' and '".$threeMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.subareaid = r.subareaid and a.tahun between '".$threeMonthArr[0]."' and '".$threeMonthArr[0]."' and a.bulan between '".$threeMonthArr[1]."' and '".$threeMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.subareaid = r.subareaid and a.tahun between '".$threeMonthArr[0]."' and '".$threeMonthArr[0]."' and a.bulan between '".$threeMonthArr[1]."' and '".$threeMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.subareaid = r.subareaid and a.tahun between '".$threeMonthArr[0]."' and '".$threeMonthArr[0]."' and a.bulan between '".$threeMonthArr[1]."' and '".$threeMonthArr[1]."') sm from m_area_subarea r where r.regionalid = '".$data['regionalid']."' and r.areaid = '".$data['areaid']."'
            union all
            select r.subareaid,r.nama_area, '".$data['inmonth']."' header, 'last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.subareaid = r.subareaid and a.tahun between '".$inMonthLastMonthArr[0]."' and '".$inMonthLastMonthArr[0]."' and a.bulan between '".$inMonthLastMonthArr[1]."' and '".$inMonthLastMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.subareaid = r.subareaid and a.tahun between '".$inMonthLastMonthArr[0]."' and '".$inMonthLastMonthArr[0]."' and a.bulan between '".$inMonthLastMonthArr[1]."' and '".$inMonthLastMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.subareaid = r.subareaid and a.tahun between '".$inMonthLastMonthArr[0]."' and '".$inMonthLastMonthArr[0]."' and a.bulan between '".$inMonthLastMonthArr[1]."' and '".$inMonthLastMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.subareaid = r.subareaid and a.tahun between '".$inMonthLastMonthArr[0]."' and '".$inMonthLastMonthArr[0]."' and a.bulan between '".$inMonthLastMonthArr[1]."' and '".$inMonthLastMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.subareaid = r.subareaid and a.tahun between '".$inMonthLastMonthArr[0]."' and '".$inMonthLastMonthArr[0]."' and a.bulan between '".$inMonthLastMonthArr[1]."' and '".$inMonthLastMonthArr[1]."') sm from m_area_subarea r where r.regionalid = '".$data['regionalid']."' and r.areaid = '".$data['areaid']."' 
            union all
            select r.subareaid,r.nama_area, '".$data['lastmonth']."' header, 'last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.subareaid = r.subareaid and a.tahun between '".$lastMonthLastMonthArr[0]."' and '".$lastMonthLastMonthArr[0]."' and a.bulan between '".$lastMonthLastMonthArr[1]."' and '".$lastMonthLastMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.subareaid = r.subareaid and a.tahun between '".$lastMonthLastMonthArr[0]."' and '".$lastMonthLastMonthArr[0]."' and a.bulan between '".$lastMonthLastMonthArr[1]."' and '".$lastMonthLastMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.subareaid = r.subareaid and a.tahun between '".$lastMonthLastMonthArr[0]."' and '".$lastMonthLastMonthArr[0]."' and a.bulan between '".$lastMonthLastMonthArr[1]."' and '".$lastMonthLastMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.subareaid = r.subareaid and a.tahun between '".$lastMonthLastMonthArr[0]."' and '".$lastMonthLastMonthArr[0]."' and a.bulan between '".$lastMonthLastMonthArr[1]."' and '".$lastMonthLastMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.subareaid = r.subareaid and a.tahun between '".$lastMonthLastMonthArr[0]."' and '".$lastMonthLastMonthArr[0]."' and a.bulan between '".$lastMonthLastMonthArr[1]."' and '".$lastMonthLastMonthArr[1]."') sm from m_area_subarea r where r.regionalid = '".$data['regionalid']."' and r.areaid = '".$data['areaid']."'
            union all
            select r.subareaid,r.nama_area, '".$data['threemonth']."' header, 'last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.subareaid = r.subareaid and a.tahun between '".$threeMonthLastMonthArr[0]."' and '".$threeMonthLastMonthArr[0]."' and a.bulan between '".$threeMonthLastMonthArr[1]."' and '".$threeMonthLastMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.subareaid = r.subareaid and a.tahun between '".$threeMonthLastMonthArr[0]."' and '".$threeMonthLastMonthArr[0]."' and a.bulan between '".$threeMonthLastMonthArr[1]."' and '".$threeMonthLastMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.subareaid = r.subareaid and a.tahun between '".$threeMonthLastMonthArr[0]."' and '".$threeMonthLastMonthArr[0]."' and a.bulan between '".$threeMonthLastMonthArr[1]."' and '".$threeMonthLastMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.subareaid = r.subareaid and a.tahun between '".$threeMonthLastMonthArr[0]."' and '".$threeMonthLastMonthArr[0]."' and a.bulan between '".$threeMonthLastMonthArr[1]."' and '".$threeMonthLastMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.subareaid = r.subareaid and a.tahun between '".$threeMonthLastMonthArr[0]."' and '".$threeMonthLastMonthArr[0]."' and a.bulan between '".$threeMonthLastMonthArr[1]."' and '".$threeMonthLastMonthArr[1]."') sm from m_area_subarea r where r.regionalid = '".$data['regionalid']."' and r.areaid = '".$data['areaid']."'
            union all
            select r.subareaid,r.nama_area, '".$data['inmonth']."' header, 'three_last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.subareaid = r.subareaid and a.tahun between '".$inMonthThreeMonthArr[0]."' and '".$inMonthThreeMonthArr[0]."' and a.bulan between '".$inMonthThreeMonthArr[1]."' and '".$inMonthThreeMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.subareaid = r.subareaid and a.tahun between '".$inMonthThreeMonthArr[0]."' and '".$inMonthThreeMonthArr[0]."' and a.bulan between '".$inMonthThreeMonthArr[1]."' and '".$inMonthThreeMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.subareaid = r.subareaid and a.tahun between '".$inMonthThreeMonthArr[0]."' and '".$inMonthThreeMonthArr[0]."' and a.bulan between '".$inMonthThreeMonthArr[1]."' and '".$inMonthThreeMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.subareaid = r.subareaid and a.tahun between '".$inMonthThreeMonthArr[0]."' and '".$inMonthThreeMonthArr[0]."' and a.bulan between '".$inMonthThreeMonthArr[1]."' and '".$inMonthThreeMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.subareaid = r.subareaid and a.tahun between '".$inMonthThreeMonthArr[0]."' and '".$inMonthThreeMonthArr[0]."' and a.bulan between '".$inMonthThreeMonthArr[1]."' and '".$inMonthThreeMonthArr[1]."') sm from m_area_subarea r where r.regionalid = '".$data['regionalid']."' and r.areaid = '".$data['areaid']."' 
            union all
            select r.subareaid,r.nama_area, '".$data['lastmonth']."' header, 'three_last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.subareaid = r.subareaid and a.tahun between '".$lastMonthThreeMonthArr[0]."' and '".$lastMonthThreeMonthArr[0]."' and a.bulan between '".$lastMonthThreeMonthArr[1]."' and '".$lastMonthThreeMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.subareaid = r.subareaid and a.tahun between '".$lastMonthThreeMonthArr[0]."' and '".$lastMonthThreeMonthArr[0]."' and a.bulan between '".$lastMonthThreeMonthArr[1]."' and '".$lastMonthThreeMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.subareaid = r.subareaid and a.tahun between '".$lastMonthThreeMonthArr[0]."' and '".$lastMonthThreeMonthArr[0]."' and a.bulan between '".$lastMonthThreeMonthArr[1]."' and '".$lastMonthThreeMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.subareaid = r.subareaid and a.tahun between '".$lastMonthThreeMonthArr[0]."' and '".$lastMonthThreeMonthArr[0]."' and a.bulan between '".$lastMonthThreeMonthArr[1]."' and '".$lastMonthThreeMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.subareaid = r.subareaid and a.tahun between '".$lastMonthThreeMonthArr[0]."' and '".$lastMonthThreeMonthArr[0]."' and a.bulan between '".$lastMonthThreeMonthArr[1]."' and '".$lastMonthThreeMonthArr[1]."') sm from m_area_subarea r where r.regionalid = '".$data['regionalid']."' and r.areaid = '".$data['areaid']."'
            union all
            select r.subareaid,r.nama_area, '".$data['threemonth']."' header, 'three_last_month' header_left, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MINIMARKET' and c.subareaid = r.subareaid and a.tahun between '".$threeMonthThreeMonthArr[0]."' and '".$threeMonthThreeMonthArr[0]."' and a.bulan between '".$threeMonthThreeMonthArr[1]."' and '".$threeMonthThreeMonthArr[1]."') mm, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'HYPERMARKET' and c.subareaid = r.subareaid and a.tahun between '".$threeMonthThreeMonthArr[0]."' and '".$threeMonthThreeMonthArr[0]."' and a.bulan between '".$threeMonthThreeMonthArr[1]."' and '".$threeMonthThreeMonthArr[1]."') hype, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MODERN PHARMA' and c.subareaid = r.subareaid and a.tahun between '".$threeMonthThreeMonthArr[0]."' and '".$threeMonthThreeMonthArr[0]."' and a.bulan between '".$threeMonthThreeMonthArr[1]."' and '".$threeMonthThreeMonthArr[1]."') mp, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'MTI' and c.subareaid = r.subareaid and a.tahun between '".$threeMonthThreeMonthArr[0]."' and '".$threeMonthThreeMonthArr[0]."' and a.bulan between '".$threeMonthThreeMonthArr[1]."' and '".$threeMonthThreeMonthArr[1]."') mti, (select round((sum(a.qty_ed * d.h_grosir)/1000000), 2) qty_ed from t_stock_all_outlet a left join m_customer b on a.customerid = b.customerid left join m_area_subarea c on b.subareaid = c.subareaid left join m_product d on a.productid = d.productid where ".$where." b.typeid = 'SUPERMARKET' and c.subareaid = r.subareaid and a.tahun between '".$threeMonthThreeMonthArr[0]."' and '".$threeMonthThreeMonthArr[0]."' and a.bulan between '".$threeMonthThreeMonthArr[1]."' and '".$threeMonthThreeMonthArr[1]."') sm from m_area_subarea r where r.regionalid = '".$data['regionalid']."' and r.areaid = '".$data['areaid']."'
            ) x order by x.subareaid, x.header_left asc";

        $query = $this->db->query($sql);

        return $query->result_array();
    }

    function getRekapSlob($data)
    {

        $where = "";

        if ($data['brandid'] != 'null') {
            $where = "b.brandid = '".$data['brandid']."' and";
            if ($data['productid'] != 'null') {
                $where = "b.productid = '".$data['productid']."' and";
            }
        }

        $sql = "select a.qty_ed, a.bulan, a.tahun, b.nama_invoice as product, (a.qty_ed*b.h_grosir) as nilai, c.typeid as channel, c.kode_outlet, c.nama_customer as outlet, d.nama_class as account, e.nama_regional as regional, f.nama_area as area, g.nama_area as subarea from t_stock_all_outlet a left join m_product b on a.productid = b.productid left join m_customer c on a.customerid = c.customerid left join m_customer_class d on c.classid = d.classid left join m_area_regional e on c.regionalid = e.regionalid left join m_area_areasite f on c.areaid = f.areaid left join m_area_subarea g on c.subareaid = g.subareaid where ".$where." c.subareaid = '".$data['subareaid']."' having a.qty_ed > 0 order by product, outlet asc";

        $query = $this->db->query($sql);

        return $query->result_array();
    }

	function get_regional()
    {
            $sql = "select a.*
						from m_area_regional a 
						order by a.regionalid asc
						";
            $query = $this->db->query($sql);

            return $query->result_array();
    }

    function get_area($data)
    {
        $sql = "select a.*
                    from m_area_areasite a 
                where a.regionalid = ?
                    order by a.nama_area asc
                    ";
        
        if (is_null(@$data["regionalid"])) 
        {
            $query = $this->db->query($sql, array("regionalid"=>"%"));
        }else{
            $query = $this->db->query($sql, array($data["regionalid"]));
        }

        return $query->result_array();
    }

    function get_subarea($data)
    {
        if ( is_null($data["regionalid"]) or is_null($data["areaid"]) ) {
            return result(new stdClass(), 400, "Parameter not allowed");
        } else {
            $sql = "select a.*
                        from m_area_subarea a 
                    where a.regionalid=? and a.areaid=?
                        order by a.nama_area asc
                        ";

            $query = $this->db->query($sql, array($data["regionalid"],$data["areaid"]));
            if (count($query->result_array()) > 0) {
                return $query->result_array();
            } else {
                return result(new stdClass(), 201, "Data Invalid!");
            }
        }
    }
}